"""Report generation service — PDF and Excel reports for estate matters.

Report types:
  1. Matter Summary (PDF) — one-page overview for court filing / client review
  2. Asset Inventory (PDF / XLSX) — full asset list with values
  3. Task Completion Audit (PDF / XLSX) — every task with status, timestamps
  4. Distribution Ledger (PDF) — all distributions with acknowledgment status
  5. Time Tracking Export (XLSX) — stub, hours per professional per matter
"""

from __future__ import annotations

import io
import logging
import re
from datetime import date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Any

from sqlalchemy import select
from sqlalchemy.orm import selectinload

from app.models.assets import Asset
from app.models.communications import Communication
from app.models.deadlines import Deadline
from app.models.enums import (
    CommunicationType,
    DeadlineStatus,
    TaskStatus,
)
from app.models.events import Event
from app.models.matters import Matter
from app.models.stakeholders import Stakeholder
from app.models.tasks import Task

if TYPE_CHECKING:
    import uuid

    from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)


# ─── Color palette (navy/gold) ──────────────────────────────────────────────

NAVY = (26, 35, 50)  # #1a2332
GOLD = (201, 168, 76)  # #c9a84c
DARK_TEXT = (30, 30, 30)
MUTED_TEXT = (120, 120, 120)
LIGHT_BG = (248, 247, 244)  # #f8f7f4
WHITE = (255, 255, 255)
BORDER = (229, 226, 219)  # #e5e2db


# ═════════════════════════════════════════════════════════════════════════════
# PDF generation helpers (ReportLab)
# ═════════════════════════════════════════════════════════════════════════════


def _rgb(color: tuple[int, int, int]) -> Any:
    from reportlab.lib.colors import Color

    return Color(color[0] / 255, color[1] / 255, color[2] / 255)


def _create_pdf_doc(title: str, buffer: io.BytesIO) -> Any:
    """Create a ReportLab SimpleDocTemplate with standard margins."""
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate

    return SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=90,
        bottomMargin=60,
        leftMargin=50,
        rightMargin=50,
        title=title,
    )


def _header_footer(canvas: Any, doc: Any, *, firm_name: str, report_title: str) -> None:
    """Draw header and footer on each page."""
    from reportlab.lib.pagesizes import letter

    width, height = letter

    # Header background
    canvas.setFillColorRGB(*[c / 255 for c in NAVY])
    canvas.rect(0, height - 70, width, 70, fill=1, stroke=0)

    # Gold accent line
    canvas.setFillColorRGB(*[c / 255 for c in GOLD])
    canvas.rect(0, height - 73, width, 3, fill=1, stroke=0)

    # Header text
    canvas.setFillColorRGB(1, 1, 1)
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(50, height - 35, firm_name or "Estate Executor")

    canvas.setFont("Helvetica", 9)
    canvas.setFillColorRGB(*[c / 255 for c in GOLD])
    canvas.drawString(50, height - 52, report_title)

    # Date on right
    canvas.setFillColorRGB(1, 1, 1)
    canvas.setFont("Helvetica", 8)
    today_str = date.today().strftime("%B %d, %Y")
    canvas.drawRightString(width - 50, height - 35, today_str)

    # Footer
    canvas.setFillColorRGB(*[c / 255 for c in MUTED_TEXT])
    canvas.setFont("Helvetica", 7)
    canvas.drawString(50, 30, "Generated by Estate Executor OS")
    canvas.drawRightString(width - 50, 30, f"Page {doc.page}")


def _section_heading(text: str) -> Any:
    """Create a styled section heading paragraph."""
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import Paragraph

    style = ParagraphStyle(
        "SectionHeading",
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=_rgb(NAVY),
        spaceBefore=18,
        spaceAfter=8,
        borderWidth=0,
        borderPadding=0,
    )
    return Paragraph(text, style)


def _body_text(text: str) -> Any:
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import Paragraph

    style = ParagraphStyle(
        "BodyText",
        fontName="Helvetica",
        fontSize=9,
        textColor=_rgb(DARK_TEXT),
        leading=13,
        spaceBefore=2,
        spaceAfter=4,
    )
    return Paragraph(text, style)


def _kv_pair(label: str, value: str) -> Any:
    return _body_text(f"<b>{label}:</b> {value}")


def _styled_table(data: list[list[str]], col_widths: list[float] | None = None) -> Any:
    """Create a styled table with navy header."""
    from reportlab.lib import colors
    from reportlab.platypus import Table, TableStyle

    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _rgb(NAVY)),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 8),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("TEXTCOLOR", (0, 1), (-1, -1), _rgb(DARK_TEXT)),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _rgb(LIGHT_BG)]),
                ("GRID", (0, 0), (-1, -1), 0.5, _rgb(BORDER)),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return t


def _format_currency(value: Decimal | float | None) -> str:
    if value is None:
        return "—"
    return f"${value:,.2f}"


def _format_date(d: date | datetime | None) -> str:
    if d is None:
        return "—"
    if isinstance(d, datetime):
        return d.strftime("%m/%d/%Y %H:%M")
    return d.strftime("%m/%d/%Y")


def _enum_label(val: Any) -> str:
    if val is None:
        return "—"
    s = val.value if hasattr(val, "value") else str(val)
    return s.replace("_", " ").title()


# ═════════════════════════════════════════════════════════════════════════════
# Excel generation helpers (openpyxl)
# ═════════════════════════════════════════════════════════════════════════════


def _create_workbook() -> Any:
    from openpyxl import Workbook

    wb = Workbook()
    return wb


def _style_excel_header(ws: Any, col_count: int) -> None:
    """Style the first row as a navy header with white text."""
    from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

    navy_fill = PatternFill(start_color="1A2332", end_color="1A2332", fill_type="solid")
    white_font = Font(name="Calibri", bold=True, color="FFFFFF", size=10)
    thin_border = Border(
        bottom=Side(style="thin", color="E5E2DB"),
    )

    for col in range(1, col_count + 1):
        cell = ws.cell(row=1, column=col)
        cell.fill = navy_fill
        cell.font = white_font
        cell.alignment = Alignment(horizontal="left", vertical="center")
        cell.border = thin_border


def _auto_width(ws: Any) -> None:
    """Auto-adjust column widths based on content."""
    for col in ws.columns:
        max_length = 0
        col_letter = col[0].column_letter
        for cell in col:
            try:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except Exception:
                pass
        ws.column_dimensions[col_letter].width = min(max_length + 4, 50)


def _freeze_header(ws: Any) -> None:
    ws.freeze_panes = "A2"


# ═════════════════════════════════════════════════════════════════════════════
# Data fetching (shared queries)
# ═════════════════════════════════════════════════════════════════════════════


async def _get_matter_with_firm(db: AsyncSession, matter_id: uuid.UUID) -> Matter:
    from app.core.exceptions import NotFoundError

    result = await db.execute(
        select(Matter).options(selectinload(Matter.firm)).where(Matter.id == matter_id)
    )
    matter = result.scalar_one_or_none()
    if matter is None:
        raise NotFoundError(detail="Matter not found")
    return matter


async def _get_stakeholders(db: AsyncSession, matter_id: uuid.UUID) -> list[Stakeholder]:
    result = await db.execute(
        select(Stakeholder)
        .where(Stakeholder.matter_id == matter_id)
        .order_by(Stakeholder.role, Stakeholder.full_name)
    )
    return list(result.scalars().all())


async def _get_tasks(db: AsyncSession, matter_id: uuid.UUID) -> list[Task]:
    result = await db.execute(
        select(Task)
        .options(selectinload(Task.assignee), selectinload(Task.completer))
        .where(Task.matter_id == matter_id)
        .order_by(Task.sort_order, Task.created_at)
    )
    return list(result.scalars().all())


async def _get_assets(db: AsyncSession, matter_id: uuid.UUID) -> list[Asset]:
    result = await db.execute(
        select(Asset).where(Asset.matter_id == matter_id).order_by(Asset.asset_type, Asset.title)
    )
    return list(result.scalars().all())


async def _get_deadlines(db: AsyncSession, matter_id: uuid.UUID) -> list[Deadline]:
    result = await db.execute(
        select(Deadline).where(Deadline.matter_id == matter_id).order_by(Deadline.due_date)
    )
    return list(result.scalars().all())


async def _get_recent_events(
    db: AsyncSession,
    matter_id: uuid.UUID,
    limit: int = 10,
) -> list[Event]:
    result = await db.execute(
        select(Event)
        .where(Event.matter_id == matter_id)
        .order_by(Event.created_at.desc())
        .limit(limit)
    )
    return list(result.scalars().all())


async def _get_distributions(db: AsyncSession, matter_id: uuid.UUID) -> list[Communication]:
    result = await db.execute(
        select(Communication)
        .options(selectinload(Communication.sender))
        .where(
            Communication.matter_id == matter_id,
            Communication.type == CommunicationType.distribution_notice,
        )
        .order_by(Communication.created_at)
    )
    return list(result.scalars().all())


# ═════════════════════════════════════════════════════════════════════════════
# Report 1: Matter Summary (PDF)
# ═════════════════════════════════════════════════════════════════════════════


async def generate_matter_summary_pdf(db: AsyncSession, *, matter_id: uuid.UUID) -> bytes:
    """Generate a one-page PDF overview of the estate."""
    from reportlab.platypus import Spacer

    matter = await _get_matter_with_firm(db, matter_id)
    stakeholders = await _get_stakeholders(db, matter_id)
    tasks = await _get_tasks(db, matter_id)
    assets = await _get_assets(db, matter_id)
    deadlines = await _get_deadlines(db, matter_id)
    recent_events = await _get_recent_events(db, matter_id, limit=8)

    firm_name = (matter.firm.name or "") if matter.firm else ""
    report_title = f"Matter Summary — Estate of {matter.decedent_name}"

    buffer = io.BytesIO()
    doc = _create_pdf_doc(report_title, buffer)

    elements: list[Any] = []

    # Matter details
    elements.append(_section_heading("Matter Details"))
    elements.append(_kv_pair("Title", matter.title))
    elements.append(_kv_pair("Decedent", matter.decedent_name))
    elements.append(_kv_pair("Estate Type", _enum_label(matter.estate_type)))
    elements.append(_kv_pair("Jurisdiction", matter.jurisdiction_state))
    elements.append(_kv_pair("Phase", _enum_label(matter.phase)))
    elements.append(_kv_pair("Status", _enum_label(matter.status)))
    if matter.date_of_death:
        elements.append(_kv_pair("Date of Death", _format_date(matter.date_of_death)))
    if matter.estimated_value:
        elements.append(_kv_pair("Estimated Value", _format_currency(matter.estimated_value)))

    # Stakeholders
    elements.append(Spacer(1, 8))
    elements.append(_section_heading("Stakeholders"))
    if stakeholders:
        sh_data = [["Name", "Role", "Email", "Status"]]
        for s in stakeholders:
            sh_data.append(
                [
                    s.full_name,
                    _enum_label(s.role),
                    s.email,
                    _enum_label(s.invite_status),
                ]
            )
        elements.append(_styled_table(sh_data, [140, 100, 180, 70]))

    # Task completion
    elements.append(Spacer(1, 8))
    elements.append(_section_heading("Task Progress"))
    total = len(tasks)
    complete = sum(1 for t in tasks if t.status in (TaskStatus.complete, TaskStatus.waived))
    overdue = sum(
        1
        for t in tasks
        if t.due_date
        and t.due_date < date.today()
        and t.status not in (TaskStatus.complete, TaskStatus.waived, TaskStatus.cancelled)
    )
    pct = round(complete / total * 100) if total > 0 else 0
    elements.append(
        _body_text(f"Total tasks: {total} | Complete: {complete} ({pct}%) | Overdue: {overdue}")
    )

    # Asset summary
    elements.append(Spacer(1, 8))
    elements.append(_section_heading("Asset Summary"))
    total_value = sum((a.current_estimated_value or Decimal(0)) for a in assets)
    elements.append(
        _body_text(
            f"Total assets: {len(assets)} | Estimated value: {_format_currency(total_value)}"
        )
    )

    # Key deadlines
    upcoming = [
        d for d in deadlines if d.status == DeadlineStatus.upcoming and d.due_date >= date.today()
    ][:5]
    if upcoming:
        elements.append(Spacer(1, 8))
        elements.append(_section_heading("Upcoming Deadlines"))
        dl_data = [["Deadline", "Due Date", "Status"]]
        for d in upcoming:
            dl_data.append([d.title, _format_date(d.due_date), _enum_label(d.status)])
        elements.append(_styled_table(dl_data, [250, 100, 80]))

    # Recent activity
    if recent_events:
        elements.append(Spacer(1, 8))
        elements.append(_section_heading("Recent Activity"))
        act_data = [["Date", "Action", "Entity", "Actor"]]
        for ev in recent_events:
            actor_label = _enum_label(ev.actor_type) if ev.actor_type else "—"
            act_data.append(
                [
                    _format_date(ev.created_at),
                    f"{ev.entity_type} {ev.action}",
                    str(ev.entity_id)[:12] + "...",
                    actor_label,
                ]
            )
        elements.append(_styled_table(act_data, [85, 120, 120, 80]))

    def on_page(canvas: Any, doc_obj: Any) -> None:
        _header_footer(canvas, doc_obj, firm_name=firm_name, report_title=report_title)

    doc.build(elements, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()


# ═════════════════════════════════════════════════════════════════════════════
# Report 2: Asset Inventory (PDF / XLSX)
# ═════════════════════════════════════════════════════════════════════════════


async def generate_asset_inventory_pdf(db: AsyncSession, *, matter_id: uuid.UUID) -> bytes:
    """Generate a PDF asset inventory report."""
    from reportlab.platypus import Spacer

    matter = await _get_matter_with_firm(db, matter_id)
    assets = await _get_assets(db, matter_id)
    firm_name = (matter.firm.name or "") if matter.firm else ""
    report_title = f"Asset Inventory — Estate of {matter.decedent_name}"

    buffer = io.BytesIO()
    doc = _create_pdf_doc(report_title, buffer)
    elements: list[Any] = []

    elements.append(_section_heading("Asset Inventory"))
    elements.append(_body_text(f"Estate of {matter.decedent_name} | {len(assets)} assets"))
    elements.append(Spacer(1, 8))

    if assets:
        data = [["Type", "Title", "Institution", "Ownership", "Value", "Status"]]
        for a in assets:
            data.append(
                [
                    _enum_label(a.asset_type),
                    a.title[:40],
                    (a.institution or "—")[:25],
                    _enum_label(a.ownership_type),
                    _format_currency(a.current_estimated_value),
                    _enum_label(a.status),
                ]
            )
        # Summary row
        total_value = sum((a.current_estimated_value or Decimal(0)) for a in assets)
        data.append(["", "", "", "TOTAL", _format_currency(total_value), ""])
        elements.append(_styled_table(data, [70, 120, 80, 70, 80, 70]))

    def on_page(canvas: Any, doc_obj: Any) -> None:
        _header_footer(canvas, doc_obj, firm_name=firm_name, report_title=report_title)

    doc.build(elements, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()


async def generate_asset_inventory_xlsx(db: AsyncSession, *, matter_id: uuid.UUID) -> bytes:
    """Generate an Excel asset inventory report."""
    await _get_matter_with_firm(db, matter_id)
    assets = await _get_assets(db, matter_id)

    wb = _create_workbook()
    ws = wb.active
    ws.title = "Asset Inventory"

    headers = [
        "Type",
        "Title",
        "Description",
        "Institution",
        "Ownership Type",
        "Transfer Mechanism",
        "Status",
        "Date of Death Value",
        "Current Estimated Value",
        "Final Appraised Value",
    ]
    ws.append(headers)
    _style_excel_header(ws, len(headers))

    for a in assets:
        ws.append(
            [
                _enum_label(a.asset_type),
                a.title,
                a.description or "",
                a.institution or "",
                _enum_label(a.ownership_type),
                _enum_label(a.transfer_mechanism),
                _enum_label(a.status),
                float(a.date_of_death_value) if a.date_of_death_value else None,
                float(a.current_estimated_value) if a.current_estimated_value else None,
                float(a.final_appraised_value) if a.final_appraised_value else None,
            ]
        )

    # Summary row
    total_row = ws.max_row + 1
    ws.cell(row=total_row, column=1, value="TOTAL")
    from openpyxl.styles import Font

    ws.cell(row=total_row, column=1).font = Font(bold=True)
    total_value = sum((a.current_estimated_value or Decimal(0)) for a in assets)
    ws.cell(row=total_row, column=9, value=float(total_value))
    ws.cell(row=total_row, column=9).font = Font(bold=True)

    _auto_width(ws)
    _freeze_header(ws)

    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()


# ═════════════════════════════════════════════════════════════════════════════
# Report 3: Task Completion Audit (PDF / XLSX)
# ═════════════════════════════════════════════════════════════════════════════


async def generate_task_audit_pdf(db: AsyncSession, *, matter_id: uuid.UUID) -> bytes:
    """Generate a PDF task completion audit report."""
    from reportlab.platypus import Spacer

    matter = await _get_matter_with_firm(db, matter_id)
    tasks = await _get_tasks(db, matter_id)
    firm_name = (matter.firm.name or "") if matter.firm else ""
    report_title = f"Task Completion Audit — Estate of {matter.decedent_name}"

    buffer = io.BytesIO()
    doc = _create_pdf_doc(report_title, buffer)
    elements: list[Any] = []

    elements.append(_section_heading("Task Completion Audit"))
    elements.append(
        _body_text(f"Estate of {matter.decedent_name} | Generated {_format_date(date.today())}")
    )
    elements.append(Spacer(1, 8))

    if tasks:
        data = [["Task", "Phase", "Assigned To", "Status", "Completed", "Completed By"]]
        for t in tasks:
            assignee_name = t.assignee.full_name if t.assignee else "—"
            completer_name = t.completer.full_name if t.completer else "—"
            data.append(
                [
                    t.title[:45],
                    _enum_label(t.phase),
                    assignee_name[:20],
                    _enum_label(t.status),
                    _format_date(t.completed_at),
                    completer_name[:20],
                ]
            )
        elements.append(_styled_table(data, [140, 70, 70, 60, 75, 70]))

    def on_page(canvas: Any, doc_obj: Any) -> None:
        _header_footer(canvas, doc_obj, firm_name=firm_name, report_title=report_title)

    doc.build(elements, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()


async def generate_task_audit_xlsx(db: AsyncSession, *, matter_id: uuid.UUID) -> bytes:
    """Generate an Excel task completion audit report."""
    await _get_matter_with_firm(db, matter_id)
    tasks = await _get_tasks(db, matter_id)

    wb = _create_workbook()
    ws = wb.active
    ws.title = "Task Audit"

    headers = [
        "Title",
        "Phase",
        "Priority",
        "Assigned To",
        "Status",
        "Due Date",
        "Completed Date",
        "Completed By",
        "Description",
    ]
    ws.append(headers)
    _style_excel_header(ws, len(headers))

    for t in tasks:
        assignee_name = t.assignee.full_name if t.assignee else ""
        completer_name = t.completer.full_name if t.completer else ""
        ws.append(
            [
                t.title,
                _enum_label(t.phase),
                _enum_label(t.priority),
                assignee_name,
                _enum_label(t.status),
                _format_date(t.due_date),
                _format_date(t.completed_at),
                completer_name,
                t.description or "",
            ]
        )

    _auto_width(ws)
    _freeze_header(ws)

    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()


# ═════════════════════════════════════════════════════════════════════════════
# Report 4: Distribution Ledger (PDF)
# ═════════════════════════════════════════════════════════════════════════════


async def generate_distribution_ledger_pdf(db: AsyncSession, *, matter_id: uuid.UUID) -> bytes:
    """Generate a PDF distribution ledger report."""
    from reportlab.platypus import Spacer

    matter = await _get_matter_with_firm(db, matter_id)
    distributions = await _get_distributions(db, matter_id)
    stakeholders = await _get_stakeholders(db, matter_id)
    firm_name = (matter.firm.name or "") if matter.firm else ""
    report_title = f"Distribution Ledger — Estate of {matter.decedent_name}"

    # Build stakeholder lookup
    sh_lookup = {str(s.id): s.full_name for s in stakeholders}

    buffer = io.BytesIO()
    doc = _create_pdf_doc(report_title, buffer)
    elements: list[Any] = []

    elements.append(_section_heading("Distribution Ledger"))
    elements.append(
        _body_text(f"Estate of {matter.decedent_name} | {len(distributions)} distribution(s)")
    )
    elements.append(Spacer(1, 8))

    if distributions:
        data = [["Date", "Beneficiary / Recipients", "Description", "Amount", "Acknowledged"]]
        for d in distributions:
            # Build recipient list from visible_to stakeholder IDs
            if d.visible_to:
                recipients = ", ".join(
                    sh_lookup.get(str(uid), str(uid)[:8]) for uid in d.visible_to
                )
            else:
                recipients = "All stakeholders"

            # Extract amount if present in subject (e.g. "$150,000")
            amount = "—"
            body_text = d.body or ""
            subject_text = d.subject or ""
            for text in [subject_text, body_text]:
                match = re.search(r"\$[\d,]+\.?\d*", text)
                if match:
                    amount = match.group(0)
                    break

            ack_count = len(d.acknowledged_by or [])
            total_visible = len(d.visible_to or [])
            ack_label = f"{ack_count}/{total_visible}" if total_visible > 0 else f"{ack_count}"

            data.append(
                [
                    _format_date(d.created_at),
                    recipients[:40],
                    (d.subject or "Distribution Notice")[:40],
                    amount,
                    ack_label,
                ]
            )
        elements.append(_styled_table(data, [70, 120, 120, 70, 60]))
    else:
        elements.append(_body_text("No distributions recorded for this matter."))

    def on_page(canvas: Any, doc_obj: Any) -> None:
        _header_footer(canvas, doc_obj, firm_name=firm_name, report_title=report_title)

    doc.build(elements, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()


# ═════════════════════════════════════════════════════════════════════════════
# Report 5: Time Tracking Export (XLSX) — stub
# ═════════════════════════════════════════════════════════════════════════════


async def generate_time_tracking_xlsx(db: AsyncSession, *, matter_id: uuid.UUID) -> bytes:
    """Generate a time tracking export with all entries and a summary sheet."""
    from app.models.time_entries import TimeEntry

    matter, firm = await _get_matter_with_firm(db, matter_id)

    # Fetch all time entries with relationships
    result = await db.execute(
        select(TimeEntry)
        .options(
            selectinload(TimeEntry.task),
            selectinload(TimeEntry.stakeholder),
        )
        .where(TimeEntry.matter_id == matter_id)
        .order_by(TimeEntry.entry_date.desc(), TimeEntry.created_at.desc())
    )
    entries = list(result.scalars().unique().all())

    wb = _create_workbook()

    # ── Sheet 1: Time Entries ──
    ws = wb.active
    ws.title = "Time Entries"

    headers = [
        "Date",
        "Professional",
        "Task",
        "Hours",
        "Minutes",
        "Decimal Hours",
        "Description",
        "Billable",
    ]
    ws.append(headers)
    _style_excel_header(ws, len(headers))

    for entry in entries:
        total_mins = entry.hours * 60 + entry.minutes
        decimal_hours = round(total_mins / 60, 2)
        ws.append([
            entry.entry_date.isoformat() if entry.entry_date else "",
            entry.stakeholder.full_name if entry.stakeholder else "",
            entry.task.title if entry.task else "(No task)",
            entry.hours,
            entry.minutes,
            decimal_hours,
            entry.description,
            "Yes" if entry.billable else "No",
        ])

    _auto_width(ws)
    _freeze_header(ws)

    # ── Sheet 2: Summary ──
    ws2 = wb.create_sheet("Summary")

    # Summary by professional
    ws2.append(["Matter:", matter.title])
    ws2.append(["Decedent:", matter.decedent_name])
    ws2.append(["Generated:", datetime.now().strftime("%Y-%m-%d %H:%M")])
    ws2.append([])
    ws2.append(["Summary by Professional"])
    ws2.append(["Professional", "Total Hours", "Billable Hours", "Non-Billable Hours"])
    _style_excel_header(ws2, 4, row=6)

    # Aggregate by professional
    prof_totals: dict[str, dict[str, float]] = {}
    for entry in entries:
        name = entry.stakeholder.full_name if entry.stakeholder else "Unknown"
        if name not in prof_totals:
            prof_totals[name] = {"total": 0, "billable": 0, "non_billable": 0}
        mins = entry.hours * 60 + entry.minutes
        prof_totals[name]["total"] += mins
        if entry.billable:
            prof_totals[name]["billable"] += mins
        else:
            prof_totals[name]["non_billable"] += mins

    for name, totals in prof_totals.items():
        ws2.append([
            name,
            round(totals["total"] / 60, 2),
            round(totals["billable"] / 60, 2),
            round(totals["non_billable"] / 60, 2),
        ])

    _auto_width(ws2)

    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()


# ═════════════════════════════════════════════════════════════════════════════
# Report dispatcher
# ═════════════════════════════════════════════════════════════════════════════


REPORT_GENERATORS: dict[str, dict[str, Any]] = {
    "matter-summary": {
        "pdf": generate_matter_summary_pdf,
        "label": "Matter Summary",
        "formats": ["pdf"],
    },
    "asset-inventory": {
        "pdf": generate_asset_inventory_pdf,
        "xlsx": generate_asset_inventory_xlsx,
        "label": "Asset Inventory",
        "formats": ["pdf", "xlsx"],
    },
    "task-audit": {
        "pdf": generate_task_audit_pdf,
        "xlsx": generate_task_audit_xlsx,
        "label": "Task Completion Audit",
        "formats": ["pdf", "xlsx"],
    },
    "distribution-ledger": {
        "pdf": generate_distribution_ledger_pdf,
        "label": "Distribution Ledger",
        "formats": ["pdf"],
    },
    "time-tracking": {
        "xlsx": generate_time_tracking_xlsx,
        "label": "Time Tracking Export",
        "formats": ["xlsx"],
    },
}


_CACHE_TTL = 86400  # 24 hours


def _get_cache_key(matter_id: uuid.UUID, report_type: str, output_format: str) -> str:
    today_str = date.today().strftime("%Y%m%d")
    return f"report:{matter_id}:{report_type}:{output_format}:{today_str}"


def _cache_get(key: str) -> bytes | None:
    """Try to get a cached report from Redis. Returns None on miss or error."""
    try:
        import redis

        from app.core.config import settings

        r = redis.from_url(settings.redis_url)
        data = r.get(key)
        r.close()
        return data  # type: ignore[return-value]
    except Exception:
        logger.debug("report_cache_miss", extra={"key": key})
        return None


def _cache_set(key: str, data: bytes) -> None:
    """Cache a generated report in Redis. Fire-and-forget."""
    try:
        import redis

        from app.core.config import settings

        r = redis.from_url(settings.redis_url)
        r.setex(key, _CACHE_TTL, data)
        r.close()
    except Exception:
        logger.debug("report_cache_set_failed", extra={"key": key})


async def generate_report(
    db: AsyncSession,
    *,
    matter_id: uuid.UUID,
    report_type: str,
    output_format: str = "pdf",
) -> tuple[bytes, str, str]:
    """Generate a report and return (bytes, filename, content_type).

    Reports are cached in Redis for 24 hours (keyed by matter, type,
    format, and date). Raises ValueError if report_type or format is invalid.
    """
    if report_type not in REPORT_GENERATORS:
        raise ValueError(f"Unknown report type: {report_type}")

    config = REPORT_GENERATORS[report_type]
    if output_format not in config["formats"]:
        raise ValueError(
            f"Format '{output_format}' not supported for '{report_type}'. "
            f"Available: {config['formats']}"
        )

    # Check cache first
    cache_key = _get_cache_key(matter_id, report_type, output_format)
    cached = _cache_get(cache_key)

    if cached is not None:
        logger.info("report_cache_hit", extra={"key": cache_key})
        content = cached
    else:
        generator = config[output_format]
        content = await generator(db, matter_id=matter_id)
        _cache_set(cache_key, content)

    matter = await _get_matter_with_firm(db, matter_id)
    safe_name = matter.decedent_name.replace(" ", "_")[:30]
    today_str = date.today().strftime("%Y%m%d")

    if output_format == "pdf":
        filename = f"{report_type}_{safe_name}_{today_str}.pdf"
        content_type = "application/pdf"
    else:
        filename = f"{report_type}_{safe_name}_{today_str}.xlsx"
        content_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

    return content, filename, content_type
