"""initial models

Revision ID: 15ca5130e6b6
Revises:
Create Date: 2026-03-22 07:15:12.143397

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "15ca5130e6b6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("matter_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.Enum("user", "system", "ai", name="actor_type"), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_events_entity_type_entity_id", "events", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        "ix_events_matter_id_created_at", "events", ["matter_id", "created_at"], unique=False
    )
    op.create_table(
        "firms",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("law_firm", "ria", "trust_company", "family_office", "other", name="firm_type"),
            nullable=False,
        ),
        sa.Column(
            "subscription_tier",
            sa.Enum("starter", "professional", "growth", "enterprise", name="subscription_tier"),
            server_default="starter",
            nullable=False,
        ),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("white_label", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("auth_provider_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_provider_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "firm_memberships",
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "firm_role", sa.Enum("owner", "admin", "member", name="firm_role"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["firm_id"], ["firms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("firm_id", "user_id", name="uq_firm_membership_firm_user"),
    )
    op.create_table(
        "matters",
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "on_hold", "closed", "archived", name="matter_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "estate_type",
            sa.Enum(
                "testate_probate",
                "intestate_probate",
                "trust_administration",
                "conservatorship",
                "mixed_probate_trust",
                "other",
                name="estate_type",
            ),
            nullable=False,
        ),
        sa.Column("jurisdiction_state", sa.String(length=2), nullable=False),
        sa.Column("date_of_death", sa.Date(), nullable=True),
        sa.Column("date_of_incapacity", sa.Date(), nullable=True),
        sa.Column("decedent_name", sa.String(), nullable=False),
        sa.Column("decedent_ssn_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "phase",
            sa.Enum("immediate", "administration", "distribution", "closing", name="matter_phase"),
            server_default="immediate",
            nullable=False,
        ),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("closed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["firm_id"], ["firms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_matters_firm_id_status", "matters", ["firm_id", "status"], unique=False)
    op.create_table(
        "assets",
        sa.Column("matter_id", sa.UUID(), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum(
                "real_estate",
                "bank_account",
                "brokerage_account",
                "retirement_account",
                "life_insurance",
                "business_interest",
                "vehicle",
                "digital_asset",
                "personal_property",
                "receivable",
                "other",
                name="asset_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("institution", sa.String(), nullable=True),
        sa.Column("account_number_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column(
            "ownership_type",
            sa.Enum(
                "in_trust",
                "joint_tenancy",
                "community_property",
                "pod_tod",
                "individual",
                "business_owned",
                "other",
                name="ownership_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "transfer_mechanism",
            sa.Enum(
                "probate",
                "trust_administration",
                "beneficiary_designation",
                "joint_survivorship",
                "other",
                name="transfer_mechanism",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("discovered", "valued", "transferred", "distributed", name="asset_status"),
            server_default="discovered",
            nullable=False,
        ),
        sa.Column("date_of_death_value", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("current_estimated_value", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("final_appraised_value", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["matter_id"], ["matters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_assets_matter_id_asset_type", "assets", ["matter_id", "asset_type"], unique=False
    )
    op.create_table(
        "entities",
        sa.Column("matter_id", sa.UUID(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "revocable_trust",
                "irrevocable_trust",
                "llc",
                "flp",
                "corporation",
                "foundation",
                "other",
                name="entity_type",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("trustee", sa.String(), nullable=True),
        sa.Column("successor_trustee", sa.String(), nullable=True),
        sa.Column("trigger_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "funding_status",
            sa.Enum(
                "unknown", "fully_funded", "partially_funded", "unfunded", name="funding_status"
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("distribution_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["matter_id"], ["matters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stakeholders",
        sa.Column("matter_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "matter_admin",
                "professional",
                "executor_trustee",
                "beneficiary",
                "read_only",
                name="stakeholder_role",
            ),
            nullable=False,
        ),
        sa.Column("relationship", sa.String(), nullable=True),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "invite_status",
            sa.Enum("pending", "accepted", "revoked", name="invite_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("invite_token", sa.String(), nullable=True),
        sa.Column(
            "notification_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["matter_id"], ["matters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invite_token"),
        sa.UniqueConstraint("matter_id", "email", name="uq_stakeholder_matter_email"),
    )
    op.create_index(
        "ix_stakeholders_matter_id_role", "stakeholders", ["matter_id", "role"], unique=False
    )
    op.create_table(
        "communications",
        sa.Column("matter_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "message",
                "milestone_notification",
                "distribution_notice",
                "document_request",
                "dispute_flag",
                name="communication_type",
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum(
                "all_stakeholders",
                "professionals_only",
                "specific",
                name="communication_visibility",
            ),
            nullable=False,
        ),
        sa.Column("visible_to", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("acknowledged_by", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["matter_id"], ["matters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["stakeholders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_communications_matter_id_type", "communications", ["matter_id", "type"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("matter_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("doc_type", sa.String(), nullable=True),
        sa.Column("doc_type_confidence", sa.Float(), nullable=True),
        sa.Column("doc_type_confirmed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("ai_extracted_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("current_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["matter_id"], ["matters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["stakeholders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_documents_matter_id_doc_type", "documents", ["matter_id", "doc_type"], unique=False
    )
    op.create_table(
        "entity_assets",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entity_id", "asset_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("matter_id", sa.UUID(), nullable=False),
        sa.Column("parent_task_id", sa.UUID(), nullable=True),
        sa.Column("template_key", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("instructions", sa.String(), nullable=True),
        sa.Column(
            "phase",
            sa.Enum(
                "immediate",
                "asset_inventory",
                "notification",
                "probate_filing",
                "tax",
                "transfer_distribution",
                "family_communication",
                "closing",
                "custom",
                name="task_phase",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "not_started",
                "in_progress",
                "blocked",
                "complete",
                "waived",
                "cancelled",
                name="task_status",
            ),
            server_default="not_started",
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("critical", "normal", "informational", name="task_priority"),
            server_default="normal",
            nullable=False,
        ),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("due_date_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("requires_document", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_by", sa.UUID(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["stakeholders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["completed_by"], ["stakeholders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["matter_id"], ["matters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tasks_matter_id_phase", "tasks", ["matter_id", "phase"], unique=False)
    op.create_index("ix_tasks_matter_id_status", "tasks", ["matter_id", "status"], unique=False)
    op.create_table(
        "asset_documents",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("asset_id", "document_id"),
    )
    op.create_table(
        "deadlines",
        sa.Column("matter_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("source", sa.Enum("auto", "manual", name="deadline_source"), nullable=False),
        sa.Column("rule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("upcoming", "completed", "extended", "missed", name="deadline_status"),
            server_default="upcoming",
            nullable=False,
        ),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column(
            "reminder_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"days_before": [30, 7, 1]}',
            nullable=False,
        ),
        sa.Column("last_reminder_sent", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["stakeholders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["matter_id"], ["matters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deadlines_matter_id_due_date_upcoming",
        "deadlines",
        ["matter_id", "due_date"],
        unique=False,
        postgresql_where=sa.text("status = 'upcoming'"),
    )
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["stakeholders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version_number", name="uq_document_version"),
    )
    op.create_table(
        "task_dependencies",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_task_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("task_id != depends_on_task_id", name="ck_task_dependency_no_self"),
        sa.ForeignKeyConstraint(["depends_on_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "depends_on_task_id", name="uq_task_dependency"),
    )
    op.create_table(
        "task_documents",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "document_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_documents")
    op.drop_table("task_dependencies")
    op.drop_table("document_versions")
    op.drop_index(
        "ix_deadlines_matter_id_due_date_upcoming",
        table_name="deadlines",
        postgresql_where=sa.text("status = 'upcoming'"),
    )
    op.drop_table("deadlines")
    op.drop_table("asset_documents")
    op.drop_index("ix_tasks_matter_id_status", table_name="tasks")
    op.drop_index("ix_tasks_matter_id_phase", table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("entity_assets")
    op.drop_index("ix_documents_matter_id_doc_type", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_communications_matter_id_type", table_name="communications")
    op.drop_table("communications")
    op.drop_index("ix_stakeholders_matter_id_role", table_name="stakeholders")
    op.drop_table("stakeholders")
    op.drop_table("entities")
    op.drop_index("ix_assets_matter_id_asset_type", table_name="assets")
    op.drop_table("assets")
    op.drop_index("ix_matters_firm_id_status", table_name="matters")
    op.drop_table("matters")
    op.drop_table("firm_memberships")
    op.drop_table("users")
    op.drop_table("firms")
    op.drop_index("ix_events_matter_id_created_at", table_name="events")
    op.drop_index("ix_events_entity_type_entity_id", table_name="events")
    op.drop_table("events")

    # Drop all PostgreSQL enum types
    for enum_name in [
        "actor_type",
        "communication_type",
        "communication_visibility",
        "deadline_source",
        "deadline_status",
        "task_priority",
        "task_status",
        "task_phase",
        "asset_status",
        "transfer_mechanism",
        "ownership_type",
        "asset_type",
        "funding_status",
        "entity_type",
        "invite_status",
        "stakeholder_role",
        "matter_phase",
        "estate_type",
        "matter_status",
        "firm_role",
        "subscription_tier",
        "firm_type",
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
